# Generated by Django 3.1.2 on 2020-10-24 09:39

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='banner',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True, verbose_name='Zdjęcie w tle'),
        ),
        migrations.AddField(
            model_name='public',
            name='verification',
            field=models.BooleanField(default=False, verbose_name='Weryfikacja profilu'),
        ),
    ]
