# Generated by Django 3.1.2 on 2020-10-24 10:06

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201024_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='video',
            field=pyuploadcare.dj.models.FileField(blank=True, null=True, verbose_name='Wideo prezentacja'),
        ),
    ]
