# Generated by Django 3.1 on 2020-09-07 18:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20200907_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPublicProfile',
            new_name='HistoricalPublic',
        ),
        migrations.RenameModel(
            old_name='PublicProfile',
            new_name='Public',
        ),
        migrations.AlterModelOptions(
            name='historicalpublic',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical public'},
        ),
    ]
