# Generated by Django 3.1 on 2020-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200907_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublic',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpublic',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
