# Generated by Django 3.1 on 2020-09-07 19:58

from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200907_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublic',
            name='avatar',
            field=models.TextField(default='', max_length=100, verbose_name='Zdjęcie profilowe'),
        ),
        migrations.AddField(
            model_name='public',
            name='avatar',
            field=optimized_image.fields.OptimizedImageField(default='', upload_to='accounts/avatar/%Y/%m/%d/', verbose_name='Zdjęcie profilowe'),
        ),
    ]
