# Generated by Django 3.1 on 2020-09-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200907_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublic',
            name='behance',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpublic',
            name='bitbucket',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpublic',
            name='deviantart',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpublic',
            name='dribbble',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpublic',
            name='flickr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpublic',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpublic',
            name='tumblr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpublic',
            name='vimeo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='behance',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='bitbucket',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='deviantart',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='dribbble',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='flickr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='tumblr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='vimeo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
