version: '3.7'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./tests/:/usr/src/locust/tests
    command: -f /usr/src/locust/tests/locustfile.py --master -H http://localhost:8000
  worker:
    image: locustio/locust
    volumes:
      - ./tests/:/usr/src/locust/tests
    command: -f /usr/src/locust/tests/locustfile.py --worker --master-host master