# Generated by Django 3.1.2 on 2020-10-23 10:28

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image_banner', pyuploadcare.dj.models.ImageField(help_text='Baner kategorii', verbose_name='Baner kategori')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Podaj tytuł wpisu który chcesz dodać', max_length=150, unique=True, verbose_name='Tytuł')),
                ('slug', models.SlugField(default='', max_length=150, unique=True)),
                ('short_description', ckeditor.fields.RichTextField(help_text='Dodaj krótki opis. Maksymalna ilość znaków to 500', max_length=500, verbose_name='Krótki opis')),
                ('description', ckeditor.fields.RichTextField(help_text='Podaj szczegółowy opis Twojego materiału.', verbose_name='Szczegółowy opis')),
                ('image_preview', pyuploadcare.dj.models.ImageField(help_text='Dodaj zdjęcie podglądowe materiału', verbose_name='Zdjęcie podglądowe')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Wybierz kategorię w której chcesz dodać wpis', on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Kategoria')),
                ('language', models.ForeignKey(help_text='Wybierz język w którym są Twoje treści', on_delete=django.db.models.deletion.CASCADE, to='blog.language', verbose_name='Język')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(help_text='Napisz szczegółowy komentarz. Wesprzyj Twórcę tego postu i przekaż swoje podziękowania lub uwagi.', verbose_name='Treść komentarza')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
