# Generated by Django 3.1.2 on 2020-10-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_banner',
        ),
    ]
