# Generated by Django 3.1 on 2020-08-06 12:43

from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='historicalblogpost',
            name='slug',
            field=models.SlugField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalblogpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_preview',
            field=optimized_image.fields.OptimizedImageField(help_text='Dodaj zdjęcie podglądowe materiału', upload_to='blog/image_blog_preview/%Y/%m/%d/', verbose_name='Zdjęcie podglądowe'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Podaj tytuł wpisu który chcesz dodać', max_length=150, unique=True, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='historicalblogpost',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalblogpost',
            name='title',
            field=models.CharField(db_index=True, help_text='Podaj tytuł wpisu który chcesz dodać', max_length=150, verbose_name='Tytuł'),
        ),
    ]
