# Generated by Django 3.0.8 on 2020-07-13 17:42

from django.db import migrations
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_preview',
            field=optimized_image.fields.OptimizedImageField(help_text='Dodaj zdjęcie podglądowe materiału', upload_to='blog/image_blog_preview/%Y/%m/%d/', verbose_name='Zdjęcie podglądowe'),
        ),
    ]
