# Generated by Django 3.1.2 on 2020-10-22 09:27

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_image_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_banner',
            field=pyuploadcare.dj.models.ImageField(help_text='Baner kategorii', verbose_name='Baner kategori'),
        ),
    ]
