# Generated by Django 3.1 on 2020-08-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200806_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='historicalblogpost',
            name='slug',
        ),
    ]
