# Generated by Django 3.1.2 on 2020-10-29 17:06

import ckeditor.fields
from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='short_description',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Treść wpisu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_preview',
            field=pyuploadcare.dj.models.ImageField(help_text='Dodaj obrazek wyróżniający Twój wpis', verbose_name='Obrazek wyróżniający'),
        ),
    ]
