# Generated by Django 3.1.2 on 2020-11-01 10:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201029_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=ckeditor.fields.RichTextField(default='', max_length=100, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Treść wpisu'),
        ),
    ]
