# Generated by Django 3.1 on 2020-08-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200806_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Podaj tytuł wpisu który chcesz dodać', max_length=150, unique=True, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='historicalblogpost',
            name='published_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalblogpost',
            name='title',
            field=models.CharField(db_index=True, help_text='Podaj tytuł wpisu który chcesz dodać', max_length=150, verbose_name='Tytuł'),
        ),
    ]
