# Generated by Django 3.1.2 on 2020-11-01 15:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201101_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Negatywna ocena'), (1, 'Pozytywna ocena')], default=1, help_text='Twoja ocena postu', verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=ckeditor.fields.RichTextField(max_length=100, verbose_name='Krótki opis'),
        ),
    ]
