# Generated by Django 3.1.2 on 2020-11-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201101_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[('Negatywna ocena', 'Negatywna ocena'), ('Pozytywna ocena', 'Pozytywna ocena')], help_text='Twoja ocena postu', verbose_name='Ocena'),
        ),
    ]
