# Generated by Django 3.1 on 2020-08-06 14:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20200806_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='HistoricalBlogCategory',
            new_name='HistoricalCategory',
        ),
        migrations.RenameModel(
            old_name='HistoricalBlogLanguage',
            new_name='HistoricalLanguage',
        ),
        migrations.RenameModel(
            old_name='HistoricalBlogPost',
            new_name='HistoricalPost',
        ),
        migrations.RenameModel(
            old_name='BlogLanguage',
            new_name='Language',
        ),
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='historicalcategory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical category'},
        ),
        migrations.AlterModelOptions(
            name='historicallanguage',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical language'},
        ),
        migrations.AlterModelOptions(
            name='historicalpost',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical post'},
        ),
    ]
