# Generated by Django 3.1.2 on 2020-11-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201101_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('Negatywna ocena', 'Negatywna ocena'), ('Pozytywna ocena', 'Pozytywna ocena')], default='Pozytywna ocena', help_text='Twoja ocena postu', max_length=100, verbose_name='Ocena'),
        ),
    ]
