# Generated by Django 3.1.3 on 2020-11-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201101_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Szkic'), (1, 'Opublikowany i publiczny')], default=0),
        ),
    ]
