# Generated by Django 3.1.3 on 2020-11-06 12:45

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201106_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=blog.models.Category, help_text='Wybierz kategorię w której chcesz dodać wpis', on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.ForeignKey(default=blog.models.Language, help_text='Wybierz język treści', on_delete=django.db.models.deletion.CASCADE, to='blog.language', verbose_name='Język'),
        ),
    ]
