# Generated by Django 3.1.2 on 2020-10-18 17:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('video', models.FileField(upload_to='courses/lessons/video/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Wpisz tytuł Twojego wideo kursu', max_length=200, verbose_name='Tytuł')),
                ('price', models.DecimalField(decimal_places=2, default='49.99', help_text='Podaj cenę w złotówkach za która chcesz sprzedawać materiał', max_digits=7, verbose_name='Cena')),
                ('short_description', ckeditor.fields.RichTextField(help_text='Dodaj krótki opis. Maksymalna ilość znaków to 500', verbose_name='Krótki opis')),
                ('description', ckeditor.fields.RichTextField(help_text='Podaj szczegółowy opis Twojego materiału.', verbose_name='Szczegółowy opis')),
                ('contests', ckeditor.fields.RichTextField(default='', help_text='Podaj zawartość i spis treści Twojego materiału', verbose_name='Zawartość i spis treści')),
                ('requirements', ckeditor.fields.RichTextField(default='', help_text='Wymagana wiedza do zrozumienia materiału', verbose_name='Wymagana wiedza')),
                ('image_preview', pyuploadcare.dj.models.ImageField(help_text='Dodaj zdjęcie podglądowe kursu', verbose_name='Zdjęcie podglądowe')),
                ('video_preview', pyuploadcare.dj.models.FileField(help_text='Dodaj film wideo reklamujący i prezentująćy Twoj wideo kurs', verbose_name='Wideo prezentacja')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Wybierz kategorię w której chcesz dodać kurs', on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory', verbose_name='Kategoria')),
                ('language', models.ForeignKey(help_text='Wybierz język w którym są Twoje treści', on_delete=django.db.models.deletion.CASCADE, to='courses.courselanguage', verbose_name='Język')),
            ],
        ),
    ]
