# Generated by Django 3.0.6 on 2020-06-04 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import optimized_image.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default='99.99', max_digits=7)),
                ('short_description', models.TextField(default='', max_length=400)),
                ('description', models.TextField(default='')),
                ('image_preview', optimized_image.fields.OptimizedImageField(default='', upload_to='image_course_preview/%Y/%m/%d/')),
                ('video_preview', models.FileField(default='', upload_to='video_course_preview/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
