# Generated by Django 3.1.2 on 2020-11-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='CourseLanguage',
            new_name='Language',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
