# Generated by Django 3.0.6 on 2020-05-28 14:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='test_text',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
