# Generated by Django 3.1rc1 on 2020-07-28 18:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(help_text='Wybierz kategorię w której chcesz dodać kurs', on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Podaj szczegółowy opis Twojego materiału.', verbose_name='Szczegółowy opis'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_preview',
            field=optimized_image.fields.OptimizedImageField(help_text='Dodaj zdjęcie podglądowe kursu', upload_to='courses/image_course_preview/%Y/%m/%d/', verbose_name='Zdjęcie podglądowe'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ForeignKey(help_text='Wybierz język w którym są Twoje treści', on_delete=django.db.models.deletion.CASCADE, to='courses.courselanguage', verbose_name='Język'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default='49.99', help_text='Podaj cenę w złotówkach za która chcesz sprzedawać materiał', max_digits=7, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=ckeditor.fields.RichTextField(help_text='Dodaj krótki opis. Maksymalna ilość znaków to 500', verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Wpisz tytuł Twojego wideo kursu', max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_preview',
            field=models.FileField(help_text='Dodaj film wideo reklamujący i prezentująćy Twoj wideo kurs', upload_to='courses/image_course_preview/%Y/%m/%d/', verbose_name='Wideo prezentacja'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Wybierz kategorię w której chcesz dodać kurs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.coursecategory', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Podaj szczegółowy opis Twojego materiału.', verbose_name='Szczegółowy opis'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='image_preview',
            field=models.TextField(help_text='Dodaj zdjęcie podglądowe kursu', max_length=100, verbose_name='Zdjęcie podglądowe'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Wybierz język w którym są Twoje treści', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.courselanguage', verbose_name='Język'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='price',
            field=models.DecimalField(decimal_places=2, default='49.99', help_text='Podaj cenę w złotówkach za która chcesz sprzedawać materiał', max_digits=7, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='short_description',
            field=ckeditor.fields.RichTextField(help_text='Dodaj krótki opis. Maksymalna ilość znaków to 500', verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='title',
            field=models.CharField(help_text='Wpisz tytuł Twojego wideo kursu', max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='video_preview',
            field=models.TextField(help_text='Dodaj film wideo reklamujący i prezentująćy Twoj wideo kurs', max_length=100, verbose_name='Wideo prezentacja'),
        ),
    ]
