# Generated by Django 3.0.6 on 2020-05-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_test_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='test_text',
        ),
    ]
