# Generated by Django 3.1 on 2020-08-04 10:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200728_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contests',
            field=ckeditor.fields.RichTextField(default='', help_text='Podaj zawartość i spis treści Twojego materiału', verbose_name='Zawartość i spis treści'),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=ckeditor.fields.RichTextField(default='', help_text='Wymagana wiedza do zrozumienia materiału', verbose_name='Wymagana wiedza'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='contests',
            field=ckeditor.fields.RichTextField(default='', help_text='Podaj zawartość i spis treści Twojego materiału', verbose_name='Zawartość i spis treści'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='requirements',
            field=ckeditor.fields.RichTextField(default='', help_text='Wymagana wiedza do zrozumienia materiału', verbose_name='Wymagana wiedza'),
        ),
    ]
