# Generated by Django 3.1.2 on 2020-11-03 05:48

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201103_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=pyuploadcare.dj.models.FileField(),
        ),
    ]
