# Generated by Django 3.1 on 2020-08-05 19:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200804_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('video', models.FileField(upload_to='courses/lessons/video/%Y/%m/%d/')),
            ],
        ),
    ]
