# Generated by Django 3.1.2 on 2020-11-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20201103_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='free_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
