# Generated by Django 3.1 on 2020-08-25 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalMentorTerms',
            new_name='HistoricalTerms',
        ),
        migrations.RenameModel(
            old_name='MentorTerms',
            new_name='Terms',
        ),
        migrations.AlterModelOptions(
            name='historicalterms',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical terms'},
        ),
    ]
