# Generated by Django 3.1 on 2020-08-25 18:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20200825_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalTerms',
            new_name='HistoricalTermsMentor',
        ),
        migrations.RenameModel(
            old_name='Terms',
            new_name='TermsMentor',
        ),
        migrations.AlterModelOptions(
            name='historicaltermsmentor',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical terms mentor'},
        ),
    ]
