# Generated by Django 3.1 on 2020-08-25 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200825_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltermsmentor',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='termsmentor',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
