# Generated by Django 3.1.2 on 2020-11-05 12:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mentors.models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tytuł to coś bardzo ważnego, zastanów się nad nim dobrze', max_length=150, verbose_name='Tytuł')),
                ('price', models.DecimalField(decimal_places=2, default='50', help_text='Ustal cenę która będziesz pobierać miesiecznie za nauczanie od każdego ucznia', max_digits=7, verbose_name='Cena')),
                ('who_am_i', ckeditor.fields.RichTextField(help_text='Napisz jak najwięcej o sobie, kim jesteś, czego nauczasz i w jaki sposób', verbose_name='Kim jestem?')),
                ('description', ckeditor.fields.RichTextField(help_text='Czym więcej informacji dla potencjalnego ucznia tym lepiej, napisz jak najwięcej.', verbose_name='Szczegółowy opis i dodatkowe informacje')),
                ('what_can_i_teach_you', ckeditor.fields.RichTextField(verbose_name='Czego mogę nauczyć')),
                ('requirements', ckeditor.fields.RichTextField(verbose_name='Moje wymagania od ucznia')),
                ('image_preview', pyuploadcare.dj.models.ImageField(verbose_name='Zdjęcie podglądowe')),
                ('video_presentation', pyuploadcare.dj.models.FileField(blank=True, null=True, verbose_name='Wideo prezentacja')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Szkic'), (1, 'Gotowe')], default=0, help_text='Status publikacji')),
                ('active', models.BooleanField(default=False, verbose_name='Zatwierdzone')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=mentors.models.Category, help_text='Wybierz kategorię w której nauczasz', on_delete=django.db.models.deletion.CASCADE, to='mentors.category', verbose_name='Kategoria')),
                ('language', models.ForeignKey(default=mentors.models.Language, help_text='Wybierz język w którym nauczasz', on_delete=django.db.models.deletion.CASCADE, to='mentors.language', verbose_name='Język')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
