# Generated by Django 3.1.2 on 2020-10-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='category',
        ),
        migrations.AddField(
            model_name='mentor',
            name='category',
            field=models.ManyToManyField(related_name='mentorzy', to='mentors.Category'),
        ),
    ]
