# Generated by Django 3.1 on 2020-08-12 17:17

from django.db import migrations, models
import django.db.models.deletion
import mentors.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_auto_20200812_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmentor',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, default=mentors.models.Category, help_text='Wybierz kategorię w której nauczasz', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mentors.category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='historicalmentor',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, default=mentors.models.Language, help_text='Wybierz język w którym nauczasz', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mentors.language', verbose_name='Język'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='category',
            field=models.ForeignKey(default=mentors.models.Category, help_text='Wybierz kategorię w której nauczasz', on_delete=django.db.models.deletion.CASCADE, to='mentors.category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='language',
            field=models.ForeignKey(default=mentors.models.Language, help_text='Wybierz język w którym nauczasz', on_delete=django.db.models.deletion.CASCADE, to='mentors.language', verbose_name='Język'),
        ),
    ]
