# Generated by Django 3.1.2 on 2020-10-22 08:09

from django.db import migrations, models
import django.db.models.deletion
import mentors.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_auto_20201022_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='category',
        ),
        migrations.AddField(
            model_name='mentor',
            name='category',
            field=models.ForeignKey(default=mentors.models.Category, help_text='Wybierz kategorię w której nauczasz', on_delete=django.db.models.deletion.CASCADE, to='mentors.category', verbose_name='Kategoria'),
        ),
    ]
