# Generated by Django 3.1 on 2020-08-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_auto_20200817_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmentor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='slug',
        ),
    ]
