# Generated by Django 3.1 on 2020-08-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_auto_20200817_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmentor',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Zatwierdzone'),
        ),
        migrations.AlterField(
            model_name='historicalmentor',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Zatwierdzone'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Tytuł'),
        ),
    ]
