# Generated by Django 3.1 on 2020-08-17 21:54

import ckeditor.fields
from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_auto_20200817_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmentor',
            name='image_preview',
            field=models.TextField(max_length=100, verbose_name='Zdjęcie podglądowe'),
        ),
        migrations.AlterField(
            model_name='historicalmentor',
            name='price',
            field=models.DecimalField(decimal_places=2, default='50', max_digits=7, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='historicalmentor',
            name='requirements',
            field=ckeditor.fields.RichTextField(verbose_name='Moje wymagania od ucznia'),
        ),
        migrations.AlterField(
            model_name='historicalmentor',
            name='video_presentation',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Wideo prezentacja'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='image_preview',
            field=optimized_image.fields.OptimizedImageField(upload_to='mentors/image_preview/%Y/%m/%d/', verbose_name='Zdjęcie podglądowe'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='price',
            field=models.DecimalField(decimal_places=2, default='50', max_digits=7, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='requirements',
            field=ckeditor.fields.RichTextField(verbose_name='Moje wymagania od ucznia'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='video_presentation',
            field=models.FileField(blank=True, null=True, upload_to='mentors/video_presentation/%Y/%m/%d/', verbose_name='Wideo prezentacja'),
        ),
    ]
