# Generated by Django 3.1 on 2020-08-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0010_auto_20200817_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmentor',
            name='status',
            field=models.IntegerField(choices=[(0, 'Szkic'), (1, 'Gotowe')], default=0, help_text='Status publikacji'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='status',
            field=models.IntegerField(choices=[(0, 'Szkic'), (1, 'Gotowe')], default=0, help_text='Status publikacji'),
        ),
    ]
