# Generated by Django 3.1 on 2020-08-25 17:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0011_auto_20200817_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmentor',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Czym więcej informacji dla potencjalnego ucznia tym lepiej, napisz jak najwięcej.', verbose_name='Szczegółowy opis i dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='historicalmentor',
            name='price',
            field=models.DecimalField(decimal_places=2, default='50', help_text='Ustal cenę która będziesz pobierać miesiecznie za nauczanie od każdego ucznia', max_digits=7, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='historicalmentor',
            name='requirements',
            field=ckeditor.fields.RichTextField(verbose_name='Wymagania od ucznia'),
        ),
        migrations.AlterField(
            model_name='historicalmentor',
            name='title',
            field=models.CharField(help_text='Tytuł to coś bardzo ważnego, zastanów się nad nim dobrze', max_length=150, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='historicalmentor',
            name='what_can_i_teach_you',
            field=ckeditor.fields.RichTextField(verbose_name='Czego nauczę'),
        ),
        migrations.AlterField(
            model_name='historicalmentor',
            name='who_am_i',
            field=ckeditor.fields.RichTextField(help_text='Napisz jak najwięcej o sobie, kim jesteś, czego nauczasz i w jaki sposób', verbose_name='Kim jestem?'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Czym więcej informacji dla potencjalnego ucznia tym lepiej, napisz jak najwięcej.', verbose_name='Szczegółowy opis i dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='price',
            field=models.DecimalField(decimal_places=2, default='50', help_text='Ustal cenę która będziesz pobierać miesiecznie za nauczanie od każdego ucznia', max_digits=7, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='requirements',
            field=ckeditor.fields.RichTextField(verbose_name='Wymagania od ucznia'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='title',
            field=models.CharField(help_text='Tytuł to coś bardzo ważnego, zastanów się nad nim dobrze', max_length=150, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='what_can_i_teach_you',
            field=ckeditor.fields.RichTextField(verbose_name='Czego nauczę'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='who_am_i',
            field=ckeditor.fields.RichTextField(help_text='Napisz jak najwięcej o sobie, kim jesteś, czego nauczasz i w jaki sposób', verbose_name='Kim jestem?'),
        ),
    ]
