# Generated by Django 3.1 on 2020-09-07 16:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0012_auto_20200825_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmentor',
            name='requirements',
            field=ckeditor.fields.RichTextField(verbose_name='Moje wymagania od ucznia'),
        ),
        migrations.AlterField(
            model_name='historicalmentor',
            name='what_can_i_teach_you',
            field=ckeditor.fields.RichTextField(verbose_name='Czego mogę nauczyć'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='requirements',
            field=ckeditor.fields.RichTextField(verbose_name='Moje wymagania od ucznia'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='what_can_i_teach_you',
            field=ckeditor.fields.RichTextField(verbose_name='Czego mogę nauczyć'),
        ),
    ]
